output   = "models"
wipe     = true
no-tests = true

[mysql]
  dbname  = "gojek_dev"
  host    = "127.0.0.1"
  port    = 3306
  user    = "root"
  pass    = "iuseNOTE4@OHAAHAI"
  sslmode = "false"
  whitelist = [
      "users",
  ]